export const homeCopy = {
  text84: "Ideas for better workflows",
  text85: "Inside automation.",
  text86: "Explore the blog",
  text01:
    "Experienced developers. Thoughtful solutions. A team that understands the work behind your workflow.",
  text02: "API",
  text03: "15+ automation specialists.",
  text04: "One connected development team.",
  text05: "BUILT WITH THE TOOLS",
  text06: "YOUR BUSINESS RELIES ON",
  text07: "Microsoft 365",
  text08: "Power Automate",
  text09: "Power Apps",
  text10: "SharePoint",
  text11: "Dataverse",
  text12: "Make work flow",
  text13: "Automate the everyday",
  text14:
    "Approvals, onboarding, reporting and recurring tasks, with fewer manual handoffs.",
  text15: "Connect your systems",
  text16:
    "Keep information moving between Microsoft 365, your CRM and the tools you already use.",
  text17: "Put intelligence to work",
  text18:
    "Document extraction and AI-assisted workflows, with people in control of the decisions.",
  text19: "Our expertise",
  text20: "From one workflow",
  text21: "to a connected business.",
  text22: "Explore all services",
  text23: "Why HashTurn",
  text24: "A development partner.",
  text25: "From first conversation",
  text26: "to the next iteration.",
  text27:
    "Good automation is more than a flow that runs. It fits your process, handles exceptions and gives your team a clear way forward.",
  text28: "Get to know HashTurn ↗",
  text29: "Process before platform",
  text30:
    "We understand the work, people and constraints before choosing the technical approach.",
  text31: "Connected expertise",
  text32:
    "Workflow, app, data and integration skills brought together around your project.",
  text33: "Built for handover",
  text34:
    "Clear documentation, agreed ownership and support scoped to your needs.",
  text35: "Flexible ways to work together",
  text36: "The right people.",
  text37: "For the work ahead.",
  text38: "FOCUSED EXPERTISE",
  text39: "Hire a developer",
  text40:
    "A defined workflow. An integration. An existing flow that needs attention. Bring in hands-on expertise for the task.",
  text41: "Find your developer ↗",
  text42: "CONNECTED DELIVERY",
  text43: "Hire a team",
  text44:
    "A broader roadmap across applications, workflows and business systems. Bring together the skills to deliver it.",
  text45: "Build your team ↗",
  text46: "Built for your world",
  text47: "Different industries.",
  text48: "A shared need to work better.",
  text49: "Explore industries ↗",
  text50: "Work in practice",
  text51: "Behind every workflow,",
  text52: "a business problem.",
  text53: "Case studies ↗",
  text54: "Have a process in mind?",
  text55:
    "Tell us what you’re trying to improve. We can discuss an approach relevant to your systems and requirements.",
  text56: "Discuss your project ↗",
  text57: "How we work",
  text58: "A clear path from idea to everyday use.",
  text59:
    "Understand the process, systems and what a useful outcome looks like.",
  text60: "Map the solution, exceptions, access and delivery scope.",
  text61: "Develop in reviewable steps and test with realistic scenarios.",
  text62: "Deploy, document and agree the next stage of support.",
  text63: "TECHNICAL LEADERSHIP. TEAM DELIVERY.",
  text64: "ZEESHAN BILAL / HASHTURN",
  text65: "Meet our technical lead",
  text66: "Technical depth.",
  text67: "A practical perspective.",
  text68: "Zeeshan Bilal",
  text69: "Lead Automation Developer",
  text70:
    "From Power Automate and Power Apps to APIs, AI and n8n, Zeeshan brings a connected view of business automation to HashTurn’s development team.",
  text71: "Meet Zeeshan ↗",
  text72: "A connected toolkit",
  text73: "The right technology for the process.",
  text74: "Power Automate",
  text75: "Power Apps",
  text76: "AI Builder",
  text77: "Copilot Studio",
  text78: "REST APIs",
  text79: "Office Scripts",
  text80: "A few useful answers",
  text81: "Before we",
  text82: "get started.",
  text83: "Have another question? ↗",
} as const;
